version: '3'
networks:
  lazarus_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
    name: lazarus_net
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - lazarus_net
    volumes:
      - ../rabbitmq/config.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 3s
      retries: 5

  coordinator:
    image: 7574-tp3
    container_name: coordinator
    command: coordinator
    networks:
      - lazarus_net
    environment:
      LAZARUS_DATADIR: ${LAZARUS_DATADIR}
    volumes:
      - ../settings.ini:/app/settings.ini:ro
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    depends_on:
      rabbitmq:
        condition: service_healthy

  server:
    image: 7574-tp3
    container_name: server_0
    command: server 0 1 collector --posts-group filter_columns_averager:3 --comments-group filter_comments:3
    networks:
      - lazarus_net
    volumes:
      - ../settings.ini:/app/settings.ini:ro
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    image: 7574-tp3
    container_name: client
    networks:
      - lazarus_net
    volumes:
      - ../settings.ini:/app/settings.ini:ro
      - ../data:/data:ro
    entrypoint: poetry run virgilius -vv /data/the-reddit-irl-dataset-posts-reduced.csv /data/the-reddit-irl-dataset-comments-reduced.csv server_0
    depends_on:
      rabbitmq:
        condition: service_healthy
