version: '3'
networks:
  lazarus_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
    name: lazarus_net
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - lazarus_net
    volumes:
      - ../rabbitmq/config.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 3s
      retries: 5

  coordinator:
    image: 7574-tp3
    container_name: coordinator
    command: coordinator
    networks:
      - lazarus_net
    volumes:
      - ./app/settings.ini:/settings.ini:ro

  client:
    image: 7574-tp3
    container_name: client
    entrypoint: poetry run virgilius -vv
    networks:
      - lazarus_net
    volumes:
      - ./app/settings.ini:/settings.ini:ro
